defaults: &defaults
  working_directory: ~/code
  docker:
  - image: cirrusci/flutter

version: 2
jobs:
  test:
    <<: *defaults
    steps:
    - checkout
    - run: flutter test

  android_beta:
    <<: *defaults
    steps:
    - checkout
    - run: cd android && bundle install

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - android_beta
